spring:
  datasource:
    url: jdbc:mysql://localhost:3307/db
    username: user
    password: password
  application:
    name: user
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
  instance:
    hostname: localhost
    