server:
  port: 8081

spring:
  application:
    name: user-api
  datasource:
    url: jdbc:mysql://localhost:3307/db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
    database-platform: org.hibernate.dialect.MySQL5Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
  instance:
    hostname: localhost
    